### ISSUE TITLE
Cache doesnt expire

### ISSUE THREAD

**Issue by manuelpoelzl** [alastairtree/LazyCache#100]
Iam using lazycache without dependency injection in .asp net core 3.0.
However, if i add something to the cache -  it doesnt expire.

i tried setting the absolute expire to DateOffset.Now.AddMinutes(10) - but it doesnt work

any ideas?

**Comment by alastairtree** [comment]
Have you tried getting the the item after the cache has expired? MemryCache, the MS library we use under the hood, triggers cache eviction based on calls into lazycache, and not on a timer, and so that might be why it appears not to work, when infact it is. See this SO for more info https://stackoverflow.com/a/42536192

**Comment by alastairtree** [comment]
Or maybe this is a result of this issue - #85

**Comment by alastairtree** [comment]
This is fixed in 2.0.5. Sorry for the delay.
