### ISSUE TITLE
Slightly alter "void Remove" to more closely match objectcache "object Remove".

### ISSUE THREAD

**Issue by granadacoder** [alastairtree/LazyCache#119]
[Use the Thumbs Up reaction to vote for this feature, and please avoid adding comments like "+1" as they create noise for others watching the issue.]

**Is your feature request related to a problem? Please describe.**

Consider changing: 

Remove to return the object, instead of "void".

https://github.com/alastairtree/LazyCache/blob/master/LazyCache/IAppCache.cs

 **void** Remove(string key);

-----------

To make it more like the "inspiration" in ObjectCache

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.objectcache.remove?view=dotnet-plat-ext-3.1

"public abstract **object** Remove"

=============================

**Describe the solution you'd like**

 **object** Remove(string key);

=============================

**Describe alternatives you've considered**

I GetAsync the item...then I (void) Remove it.

    ////private readonly IAppCache cache;
        public async Task<TEntity> RemoveCacheAsideItemAsync(string uniqueIdentifier)
        {
            string cacheKey = uniqueIdentifier; //  this.GetFullCacheKey(uniqueIdentifier);
            TEntity returnItem = await this.cache.GetAsync<TEntity>(cacheKey);
            this.cache.Remove(cacheKey);
            return returnItem;
        }

**Comment by alastairtree** [comment]
Thank you for your suggestion.

Because LazyCache is really just a wrapper for MemoryCache (rather than ObjectCache from .NET framework as it was previously) we mirror the API from [IMemoryCache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.imemorycache.remove?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Caching_Memory_IMemoryCache_Remove_System_Object_) in IAppCache. IMemoryCache does return void on `Remove(..).` 

This will be done for performance reasons - if you do not need the item you are removing, there is no need to pass extra references around for and delay it's garbage collection. As you have shown when you do need it you can call `Get(..)` and then `Remove(..)`.

Hope you don't mind but will now close this issue as a 'wont fix' but feel free to make any other suggestions!
