### ISSUE TITLE
Why return await?

### ISSUE THREAD

**Issue by burnchar** [alastairtree/LazyCache#32]
It looks as if LazyCache's async methods `return await`.
While I do not consider myself an async code expert, my understanding is that this eliminates much of the utility of async code because all tasks are resolved before the return to the caller.
For example, if I have three mutually independent tasks that require 3 seconds of runtime each, if I await them individually as _appears_ to be done with LazyCache, the total run time is 9 seconds, whereas if I `Task.WaitAll` the tasks, total run time is 3 seconds plus overhead.
Why not return without await?

**Comment by alastairtree** [comment]
Thanks for your comment. AFAIK If a method only has one await, and it is the return line, then you are correct that the method does not need to be async/await at all, and you can just return the task. If you need to await in more than one place and must do so sequentially (as in lazy cache), then the compiler demands that you must return the result and not the task, so you have to `return await`. 

When you await inside a method, execution does return to the caller while it is 'awaited' since you are inside the task, allowing the thread to do something else while you wait for the result. When the awaited code is complete then the rest of your method can continue to execute. Async/Await is really just syntax to generate good asynchronous code by the compiler - it cannot make an operation faster (in fact there is an overhead so it makes it marginally slower!). However it does allow you to parallelise operations as you described, and it frees up threads that would otherwise be waiting for stuff so they can do other useful stuff, making your app capable of handling greater concurrency.
Does that help at all?!
I will have a look and make sure I am not unnecessarily await a task I could just return!
