### ISSUE TITLE
Generic Type Keys

### ISSUE THREAD

**Issue by mansoor945** [alastairtree/LazyCache#36]
Hi @alastairtree ,

I have started using your LazyCache library and it works great.

If you can support Generic Type Keys, it would be great. Right now only `string` type is supported as keys.

# Usage:

I have an `object` which identifies unique request which is made to database server. I want to cache the response of the database query, and for that I want the key to be set that `object`.

**Comment by alastairtree** [comment]
Can you give an example of what you mean as not sure I follow? What sort of syntax would you like? If you just wanted to use the cached item type as a key you could easily write an extension method that used the types of the existing generic parameter to generate a string based on namespace and type name for example.

**Comment by mansoor945** [comment]
Right now I am using Concurrent Dictionary in which the key is GenericType:
`ConcurrentDictionary<RequestIdentity, Action<IDbCommand, object>>`.

I am looking for something same like this `IAppCache.Add<T1, T2>(T1 key, T2 item) `

**Comment by alastairtree** [comment]
The problem with adding this to LazyCache is it means that you cannot cache 2 objects of the same type, as the second one would replace the first. This might lead to unexpected issues for an inexperienced user. Why not just add an extension method in your project that converted from type to string key by reflecting on the name, something like `var key = typeof(T1).FullName;`. Some extension methods for inspiration are in https://github.com/alastairtree/LazyCache/blob/feat/netcore2/LazyCache/AppCacheExtenions.cs

**Comment by tanbchr** [comment]
@alastairtree: I can understand the problem that we can have by adding that feature in the library. However, we did some custom code on our end to bypass that issue. We basically implemented a multi-layer cache that uses internally a ConcurrentDictionary of ConcurrentDictionary. The key of the first dictionary is a string and then they key of the other dictionary is generic. The problem with that solution is that it's very limited, we don't have all the features of MemoryCache, which enables the developer to manipulate the cache based on the time and memory. 

It will be really great if we can enhance the LazyCache and add the requested feature in it. I know it will be hard, since LazyCache is coded over the MemoryCache which does not support generic keys. A lot of people already complained about that limitation in the past.

**Comment by alastairtree** [comment]
I think you could solve this with a simple extension method like the below that uses the type name as the key? I would not build it into LazyCache as may confuse new developers but no reason not to add it into your project? You could also tweak it to use a different type param as the key like in your example.

```csharp
namespace LazyCache
{
    public static class AppCacheExtenions
    {
        public static T GetOrAdd<T>(this IAppCache cache, Func<T> addItemFactory)
        {
            if (cache == null) throw new ArgumentNullException(nameof(cache));

            var key = typeof(T).FullName;

            return cache.GetOrAdd(key, addItemFactory);
        }
    }
}
```
