### ISSUE TITLE
Consider not deprecating default constructor?

### ISSUE THREAD

**Issue by BrianVallelunga** [alastairtree/LazyCache#44]
For uses without dependency injection, such as an F# webjob I'm working on now, please consider not removing the default constructor, or have another way of building the CachingService. I'm not using dependency injection since that isn't as common among functional applications and instead need a single, long-lived instance of the CachingService in my app.

**Comment by BrianVallelunga** [comment]
A builder method would be perfectly fine for my needs. I just think assuming a DI system is in use is probably too big of an assumption, especially outside of ASP.NET Core.

**Comment by NeilMacMullen** [comment]
Agree with Brian here - LazyCache has lots of applications in other domains.

**Comment by jboarman** [comment]
I came fully-prepared with my own screenshot and all just to create an issue on this very topic.  I'm glad to see that I'm not the only one that has this concern.

![image](https://user-images.githubusercontent.com/1108065/43040332-fbe4e57a-8d06-11e8-89ba-177c2f19e6b5.png)

Everyone is going opinionated these days, and that just means fewer people can make use of an otherwise perfectly good tool!  😅

OK, I'm fine with a _small tax_ in order to swim against the current. 🏊

**Comment by alastairtree** [comment]
Ok, I concede and agree not to deprecate :-)
