### ISSUE TITLE
Auto-refresh feature for LazyCache

### ISSUE THREAD

**Issue by RuddyR** [alastairtree/LazyCache#52]
First of all, this is a awesome library!
We tried to use your implementation for a thread-safe cache usage and also be able to auto-refresh our cached object. We wanted to define for each cached object an absolute expiration time ,execute the delegate to create a new object before the cached object is removed and replace the expired object with the new object using the UpdateCallback delegate. That way the cached item would be reevaluate after the expiration time. We didn’t succeed because it is impossible to define an UpdateCallback in lazy cache. Looking online we found a way to do just that, and we thought maybe you could include that feature into the lazy cache library.
Here’s the link:
https://www.programmingmusings.com/index.php/2016/09/27/auto-refresh-thread-safe-cache-in-net/

Thank you very much and have a nice day.

**Comment by Miggleness** [comment]
I think that violates the "lazy" part of LazyCache 😄

**Comment by jemeric** [comment]
> I think that violates the "lazy" part of LazyCache 😄

I disagree, I think it can still be automatically reloaded in a lazy fashion. The idea being when you make the first request to a cached item post-expiry it will asynchronously try to fetch its new value, returning its old value until the new one is ready. It's still only done on an "at request" or "lazy" basis.

For use cases where performance is more of a concern than data consistency I believe this is a far better solution than blocking all requests until the new data is available.

**Comment by Miggleness** [comment]
Gotcha.  I understand your use case better.  I understood your earlier post as update the cache on expiry.

> That way the cached item would be reevaluate after the expiration time.

What you're looking for is along the lines from your link
> Refreshing the item in the cache will not block other threads trying to retrieve the item from the cache (they will be served the current cached item till the retrieve delegate returns the new item).

**Comment by alastairtree** [comment]
Like the idea - would need to consider carefully how to build it in not to interfer with the default Lazy behaviour. Keep the thumbs up coming to see how popular this is.

**Comment by RubberChickenParadise** [comment]
I have solved this in a previous application (with out lazy cache) by having hangfire.io create a task to refresh the cache before expiration and set a new absolute cache timeout.  It worked very well.  If for some reason hangfire had not fired the get or add would trigger as a fallback.

option 2: Lazy cache exposes the cache EvictionCallback you could possibly add the code here to add it back to the cache post eviction.

**Comment by alastairtree** [comment]
Auto refresh is now possible in LazyCache 2.1 using the ImmediateExpiration feature. See the [auto refresh example API Docs](https://github.com/alastairtree/LazyCache/wiki/API-documentation-(v-2.x)#using-immediateexpiration-and-registerpostevictioncallback-to-refresh-the-cache-automatically) for a full example.

**Comment by GeeWee** [comment]
I actually don't think this issue should be closed entirely. Often in an auto-refreshing feature here we're looking for the following functionality.
- Cache item lasts lasts 30 minutes in cache
- After 25 minutes we'd like to replace the object and refresh the duration
- While we fetch the new cache item, we'd still like to serve the old
At no point do we ever block on the refresh.

If I understand it correctly using `ImmdediatEviction` and `RegisterPostEvictionCallback` the following will happen.
- Cache item lasts 30 minutes in cache
- After 30 minutes the cache item is evicted
- The PostEviction callback is fired. Any threads that want to access the item currently are blocked.
- The PostEviction callback repopulates the cache.
At this point we do block on the cache while the PostEviction callback runs.

Is this correctly understood? If so, I think this issue should be reopened.

**Comment by RubberChickenParadise** [comment]
@GeeWee i actually had to solve that same issue.  None of the caching solutions I saw had a good solution so I used hangfire with a server specific queue and a scheduled job.  It did bring in another dependency but allowed us to get exactly the functionality you are asking for.

I think the issue is going to be tracking how long things have been in cache when they could be removed early due to memory pressure, since the underlying cache provider is Microsoft.Extensions.MemoryCache

**Comment by alastairtree** [comment]
@GeeWee if you need to do preemptive cache item regeneration then yes that work needs to happen outside of LazyCache currently. Something like Hangfire may be a good fit here, or an aspnet background service. 

It's hard to build into LazyCache because you need a set of objects with lifetimes and scopes outside the current LazyCache instance, and your runtime environment (aspnet, desktop app, background service) means you may wish to handle this differently depending on how you are running it, whether or not you use DI, etc, so it's harder to generalise a solution. 

Something like the below might work, but you can see there are a few pitfalls.

- when item is requested generate the item and cache for X minutes.
- use task.delay with time X minus 10s (say) to get notification just before invalidation. Or one-off timer you will need to clean up after.
- you may need to use DI to reacquire an instance of IAppCache. ServiceProvider/Locator anti-pattern warnings may apply.
- regenerate item and add to cache for X minutes.
- Return to step 2
