### ISSUE TITLE
Cannot convert to new Func<ICacheEntry, List<MyPoco>>

### ISSUE THREAD

**Issue by Jogai** [alastairtree/LazyCache#58]
Following the quickstart I got a comilation error on this:

`Func<IEnumerable<MyPoco>> myGetter = () => new MyLogic(dbContext).GetPoco("string");`

The error is 

```
Argument 2: cannot convert from 'Func<IEnumerable<MyPoco>>' to 'Func<ICacheEntry, List<MyPoco>>
```

Relevant nuget packages:

```
  <package id="LazyCache" version="2.0.0-beta03" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Memory" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Net.Compilers" version="2.10.0" targetFramework="net472" developmentDependency="true" />
  <package id="Microsoft.NETCore.Platforms" version="2.2.0" targetFramework="net472" />
  <package id="NETStandard.Library" version="2.0.3" targetFramework="net472" />
```

**Comment by alastairtree** [comment]
Can you share the rest of your code please? The follow example works for me, and should cover your use case I believe.

```csharp
IAppCache cache = new CachingService(CachingService.DefaultCacheProvider);
Func<Tuple<string, DateTime>> addItemFactory = () => Tuple.Create("Joe Blogs", DateTime.UtcNow);
var item = cache.GetOrAdd("Program.Main.Person", addItemFactory);
System.Console.WriteLine(item.Item1);
```

**Comment by Jogai** [comment]
I'm sorry, I cant find the offending code anymore. I was using some self-written lazy cache and switched this out for this project. I also did go back to 0.7.1.44. It could be that the reference was still pointing to my cache utility which had a very similar signature.

**Comment by klamomd** [comment]
To anyone who comes across this in the future, I had this same problem but thankfully it was just a result of me being dumb!

 I was attempting to use a Func<CustomClassA, (bool, CustomClassB)> that would pass a CustomClassA as a parameter into the delegate function afterwards. The code looked something like this (some names lazily-switched out for privacy):

`Alpha identifier = "whatever";
Func<Alpha, (bool, Charlie)> dataFetchDelegate = (Alpha a) => Lookup.TryGetCharlie(a);
(bool success, Charlie c) = cache.GetOrAdd<Alpha, (bool, Charlie)>(identifier, dataFetchDelegate);`

Turns out I didn't actually need a Func that took parameters, I just needed to get a parameter to the dataFetchDelegate to get a result from a given identifier. So I just made sure the dataFetchDelegate is created within the scope of a function call, and that the delegate definition hands that parameter to the underlying function. My updated code (which I haven't run yet, but have verified the compiler has stopped complaining) is as follows:

```
public bool TryGetCharlie(Alpha identifier, out Charlie results)
{
	
	results = null;

	Func<(bool, Charlie)> dataFetchDelegate  = () => Lookup.TryGetCharlie(identifier);
	(bool success, Charlie c) = cache.GetOrAdd<(bool, Charlie)>(identifier, dataFetchDelegate);

	if (!success) return false;

	results = charlie;
	return true;
}
```
