### ISSUE TITLE
Mocking IAppCache with AppCacheExtenions Extension Methods

### ISSUE THREAD

**Issue by justinkneff** [alastairtree/LazyCache#88]
In version .7.1.44 there was the ability to use Moq to mock the values of the IAppCache because the implementation was on the [CachingService.](https://github.com/alastairtree/LazyCache/blob/v0.7.1.44/LazyCache/CachingService.cs). When upgrading to 2.0.1 that implementation is now extension methods inside of [AppCacheExtensions](https://github.com/alastairtree/LazyCache/blob/2.0.1/LazyCache/AppCacheExtensions.cs).
Looking at the [Unit Tests](https://github.com/alastairtree/LazyCache/blob/master/LazyCache.UnitTests/CachingServiceMemoryCacheProviderTests.cs) there doesn't appear to be anything mocking the setup because it does the full implementation using the BuildCache() function in the Setup of the unit tests.
Is there a way to use mocking of the Interface without extension methods requiring the implementation of the actual service?

**Comment by alastairtree** [comment]
Sorry for the slow reply - have been deidicating more time to other projects this year. Hopfully you solved this yourself by now but will reply here for others to find later.

When I unit test code using LazyCache I tend to just use a real instance of the CachingService since it has no external dependencies and it is usually part of the thing I want to test. However if I really need to isolate the caching I use the `MockCachingService()` implementation in the `LazyCache.Mocks` namespace. See the [Unit Testing](https://github.com/alastairtree/LazyCache/wiki/Unit-testing-code-using-LazyCache) docs for more info.
